{% set version = "0.5.2" %}
{% set name = "whichcraft" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fecddd531f237ffc5db8b215409afb18fa30300699064cca4817521b4fc81815

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  source_files:
    - test_whichcraft.py
  requires:
    - pytest
  imports:
    - whichcraft
  commands:
    - pytest

about:
  home: https://github.com/pydanny/whichcraft
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: >
            This package provides cross-platform cross-python shutil.which
            functionality.

extra:
  recipe-maintainers:
    - bollwyvl
    - pydanny
