# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "kNQYk90+RxqW+X/nKAsFqT3ofLdzbMXH25ol8fNJPJoZGNSCcvrJGEiI+42ay2aY1ppEDVJtyAtd0wO5axl+k9MaoncTxqOIq8jZADAiyaF3jVq0rMEqpV3fMBKgimZ1tB3sDiUCkyhvRQgH5lNByLyBizXetNG3eDE1O7W4FjjrOlv3FClr9A7YA7w5Lx3mQc7/CQdvjLZ4QmZRFTESEjizhklNeBkCJnRdd/2Qee7a0Ml997Q0GMd44vFE8O+cc1eaiykQoBcc0tERR2Un7OEZ8pWjFv29l4Dmm4up+JtPndRTWpqdqRgAI4z8dUzd6bkvBCSJMC1Wl2Lixge+qgoU4tm3K/arL61tuScyIen40Vmt+A4qJNmD+wLWVeC3kpjnkxdkpO10g02LERO0IR01/34pO7gUkHC2xH+gu6gYhzv6fqfGHzJiciwdoxHeF05fyjWbFIbKqQ+nkPzRz1irshwoQFbl0ALeI093Lim48S0UZrHebM39WGvNgEBvzptBgNug6rV+JHsB+xMjZGD4mKdnYWEhNIV2t0z+hGpwDyxbWdvZLKMzq658HCqHFtd9eOMt00j3LDx/EY/2hQSNIM3Qi8G6t4wSJe1LQVLxsXB3rGqu4BHEBEIyFdMn8NV4OYX64b9j5rwApXW3gvgSU2aBu8P/XUJhiDPqygU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
