# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "kNQYk90+RxqW+X/nKAsFqT3ofLdzbMXH25ol8fNJPJoZGNSCcvrJGEiI+42ay2aY1ppEDVJtyAtd0wO5axl+k9MaoncTxqOIq8jZADAiyaF3jVq0rMEqpV3fMBKgimZ1tB3sDiUCkyhvRQgH5lNByLyBizXetNG3eDE1O7W4FjjrOlv3FClr9A7YA7w5Lx3mQc7/CQdvjLZ4QmZRFTESEjizhklNeBkCJnRdd/2Qee7a0Ml997Q0GMd44vFE8O+cc1eaiykQoBcc0tERR2Un7OEZ8pWjFv29l4Dmm4up+JtPndRTWpqdqRgAI4z8dUzd6bkvBCSJMC1Wl2Lixge+qgoU4tm3K/arL61tuScyIen40Vmt+A4qJNmD+wLWVeC3kpjnkxdkpO10g02LERO0IR01/34pO7gUkHC2xH+gu6gYhzv6fqfGHzJiciwdoxHeF05fyjWbFIbKqQ+nkPzRz1irshwoQFbl0ALeI093Lim48S0UZrHebM39WGvNgEBvzptBgNug6rV+JHsB+xMjZGD4mKdnYWEhNIV2t0z+hGpwDyxbWdvZLKMzq658HCqHFtd9eOMt00j3LDx/EY/2hQSNIM3Qi8G6t4wSJe1LQVLxsXB3rGqu4BHEBEIyFdMn8NV4OYX64b9j5rwApXW3gvgSU2aBu8P/XUJhiDPqygU="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
