travis:
  secure:
    BINSTAR_TOKEN: c772Xda0DCx5+2nF6fT/oLVj3uLrhs/LSqKGPAejxTI7xjBN/3WQqElEg+0gJmRE2zC5yk6YIDfK9ZHnRRw5sltjbrYZvj6SKVn9vuQdqwewjxqqayjUmm0u1zwOGHRDcadqX2qvIK7fR1Y+YmUJ0Wx/VNpJa/89azJJrJ8J1vymB0ysScMMS2rVzNNlOL0iUPtGqezwWpdvBz2MtrJ7dAPTw9rIA82WN6URAaR9EJQx/F4U4jKXhPjOsAPO+9iboXA6DWfPsqHcROOYnETk+F+LKA8iE8YzoHjNbIVYLRK/vu0Iph3DKRJfkX1SlVhotX2cjcJlEmf+42eRU1hP73LMYf//hrcEd5nwq3YUTY3XFXup1jsL8W6GwsvGZEwkdqtNx2vxpr0dJpvWwKLJYEZIoG17OiDRTXrqKxYlfuTnwz4b6WjeFzXPSupB6U0/EKp3MQr2PFfwO0fLxx8FVinZBFjIyPcBeCOUO6jviDKvXOaEgqfqqinafOYbl2HvP1O7bzIgJKs5V1ZHdntUwXqtaahmP65t6/UxCDKJ3Vcdz041A2GPGfQhahgsHkjp2PnCrjDNBU64KlTib5hrhamt50BQxe1soQUFw4qlHUiDEmwD1T0zp97ZVKeE6+bjvZrwqltU50JVSQnt/EHaeSj5FacnYd5tLx/hI/hcCyk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
