travis:
  secure:
    BINSTAR_TOKEN: DrlSoT/pitBbzB7Z6Kj9sW69uQmtRpZIb0hmDjxZiCZIhNwuSXE+91Muz+rxipZ7xgNsqwSFslN22yAFxV1QRUOuOhb21865FvedzLEDhRmYdnsGPz6nXO33m7IaFCX+pWmVQPHMChHzhTYDXP59+TBzGnbJfWrSmNbviJa4uPbtTzGR2BezdnAt7JHgKG/9rCdMnlf3NNTtFkdXSH1pqBH+8jAe9xIXri8Ws0b2qnsHv6Rj/8DsBCAUScnpSKVT+0rXC6yMDHbg48DDuI9bpeZgE5teYDtqk0FTO+QSWJkcXxeTjg97WnyWC1Pa8EKOmv3V2CCL1zGxej52Nai/cxpTt+wku+sCCWIRe0+FJR6YImQ9nyfdE5GAM/EKxLWwzgGnb7uG8VNb/8CRdCz9jCW21Kg0KFcromNP2tQFA9KkZkiSfJQ0zwchsNxy6+zcTXBGqomjTxaYf8FTugYYXz7bhvtD5NNS26krHFjYO70NvR62g6Si2eiYKAK1qOk0LubF+jRG/DZGi2GKwpYYHMxAPvMUZ29IeTbgcOMgCbNaTnpPCFzEYo1SKFdq2ekGM0LUwsjcmtkOoehzpOZrj7uIupzfOwvDoZwKVA573dBOEn8hna5l/5S9CLZe8DggsF8vfMXAQUjm4ou38xDyEQ8+dDgcpyrjErLj+Yc+e0Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
